version: '2'
services:
  django:
    build: .
    environment:
    - PYTHONUNBUFFERED=0
    - GEOSERVER_PUBLIC_LOCATION=http://localhost:8080/geoserver/
    depends_on:
      - postgres
    command: python manage.py runserver 0.0.0.0:8000
    networks:
      backend:
    ports:
      - "8000:8000"
    volumes:
     - '.:/app'

  postgres:
    image: mdillon/postgis:9.3
    environment:
     - POSTGRES_USER=osgeo
     - POSTGRES_PASSWORD=osgeo
     - POSTGRES_DB=osgeo_importer_test
    networks:
      backend:
    ports:
     - "5432:5432"
    expose:
     - "5432"
  geoserver:
    build: "geoserver/"
    image: "geoserver-host-postgres:2.9.2"
    networks:
      backend:
    ports:
     - "8080:8080"
    expose:
     - "8080"
    links:
     - postgres
    volumes:
     - '.:/app'

networks:
  backend:
